### ISSUE TITLE
f5 not quitting the terminal program on mac 

### ISSUE THREAD

**Issue by Aslan** [jmespath/jmespath.terminal#1]
running mac 10.9.5. and zsh(oh-my-zsh). When i press F5 i get a denied sign on the screen 
![image](https://cloud.githubusercontent.com/assets/28365/5058776/a916535a-6cb3-11e4-9365-40ff5c264fc1.png)

**Comment by RichardBronosky** [comment]
@Aslan is this still an issue? If so, please answer these questions:
- What terminal application are you using on your Mac? (I am using iTerm 2.0.0.20141103)
- Please share the output of `env | grep TERM` (I get...)

```
$ env | grep TERM
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
ITERM_PROFILE=Default
ITERM_SESSION_ID=w4t1p0
```
- Please share the output of `python -m curtsies.events` (I get...)

```
$ python -m curtsies.events
press a bunch of keys (not at the same time, but you can hit them pretty quickly)
---
'\x1b[15~'
<F5>
```

On my machine I am unable to reproduce your issue. If your issue is resolved, Please close it.

**Comment by Aslan** [comment]
resolved now.
